### ISSUE TITLE
[Feature] 하단 바 찜하기 버튼 구현하였습니다.

### ISSUE THREAD

**Issue by boyeon0119** [DO-SOPT-CDS-APP-7/Kurly-iOS#47]
## 🛠 Issue

- 찜하기 버튼 선택 시, 채워진 하트 이미지로 변경
- 찜하기 버튼 재선택 시, 비어있는 하트 이미지로 변경

## 📝 To-do

- [ ] 하단 바 영역 레이아웃 잡기
- [ ] 찜하기 버튼 만들기
- [ ] 찜하기 버튼 동작에 따른 하트 이미지 변경
