### ISSUE TITLE
[Feature] 상품 결제 금액에 관한 로직을 구현합니다.

### ISSUE THREAD

**Issue by Genesis2010** [DO-SOPT-CDS-APP-7/Kurly-iOS#68]
## 🛠 Issue

- 서버에서는 상품 가격과 할인 비율을 알려주기 때문에 그에 알맞는 동작을 구현하고자합니다.

## 📝 To-do

- [ ] 상품 가격과 할인율을 통해 할인된 가격 구하기
- [ ] 하단의 버튼에 가격 표시하기
- [ ] stepper 를 눌러 상품 개수 변경 및 가격 변경
